[tools]
"github:microsoft/apm" = "0.31.0"
claude = "latest"
"aqua:sigoden/aichat" = "latest"
"aqua:openai/codex" = "latest"
"aqua:anomalyco/opencode" = "latest"
"npm:@github/copilot-language-server" = "1.463.0"
"npm:@loongphy/codex-auth" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@tobilu/qmd" = "latest"
"npm:@plannotator/pi-extension" = { version = "latest", trust_policy_excludes = ["@pierre/theme@2.0.0"]}
