[tools]
atuin = "latest"
doggo = "latest"
eza = "latest"
fzf = "latest"
herdr = "latest"
jq = "latest"
just = "latest"
starship = "latest"
usage = "latest"
zoxide = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ClementTsang/bottom" = "latest"
"aqua:bootandy/dust" = "latest"
"aqua:carapace-sh/carapace-bin" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:dalance/procs" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:fastfetch-cli/fastfetch" = "latest"
"aqua:ip7z/7zip" = "latest"
"aqua:ynqa/jnv" = "latest"
"aqua:joshmedeski/sesh" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:muesli/duf" = "latest"
"aqua:o2sh/onefetch" = "latest"
"aqua:rclone/rclone" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/hyperfine" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:dduan/tre" = "latest"
