[tools]
biome = "latest"
lua-language-server = "latest"
oxfmt = "latest"
prettier = "latest"
shellcheck = "latest"
stylua = "latest"
tombi = "latest"
tree-sitter = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:fish-lsp" = "latest"
"npm:typescript" = "5"
"npm:typescript-language-server" = "5.3.0"
"npm:vscode-langservers-extracted" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:img2art" = "latest"
"pipx:poetry" = "latest"
"pipx:posting" = "latest"
"pipx:pre-commit" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:goreleaser/goreleaser" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:rhysd/actionlint" = "latest"
"npm:@tailwindcss/language-server" = "latest"
